package flentities

// AmenityType represents a recognized amenity type
type AmenityType struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// PropertyAmenityTypes supported by the system
var PropertyAmenityTypes = []*AmenityType{
	{"24-hour-concierge", "24-hour Concierge Service"},
	{"24-hour-maintenance", "24-hour Maintenance Services"},
	{"24-hour-security", "24-hour Security"},
	{"airport-pick-up", "Airport Pick Up"},
	{"art-gallery", "Art Gallery"},
	{"babysiting", "Babysiting Service"},
	{"business-centre", "Business Centre"},
	{"car-park", "Car Park"},
	{"childrens-party-room", "Children's Party Room"},
	{"complimentary-newspaper-magazine", "Complimentary Newspaper and Magazine"},
	{"computer-workstations", "Computer Workstations"},
	{"concierge", "Concierge"},
	{"daily-maid", "Daily Maid Service"},
	{"daycare", "Daycare"},
	{"dedicated-mobile-app", "Dedicated Mobile App"},
	{"disabled-room", "Disabled Room"},
	{"dry-cleaning", "Dry Cleaning"},
	{"dvd-library", "DVD Library"},
	{"e-centre", "E-Centre"},
	{"evening-turndown", "Evening Turndown Service"},
	{"fitness room", "Fitness Room"},
	{"flexible-terms", "Flexible Terms"},
	{"food-delivery-service", "Food Delivery Service"},
	{"foreign-exchange", "Foreign Exchange"},
	{"gift-shop", "Gift Shop"},
	{"gym", "Gym"},
	{"indoor-basketball-court", "Indoor Basketball Court"},
	{"indoor-childrens-playroom", "Indoor Children's Playroom"},
	{"it-engineering-support", "IT & Engineering Support"},
	{"karaoke-room", "Karaoke Room"},
	{"laundry", "Laundry"},
	{"library", "Library"},
	{"lifestyle-cafe", "Lifestyle Café"},
	{"limousine", "Limousine Service"},
	{"mail-message-delivery", "Mail and Message Delivery"},
	{"medical-assistance-referrals", "Medical Assistance Referrals"},
	{"meeting-rooms", "Meeting Rooms"},
	{"mini-mart", "Mini-Mart"},
	{"multilingual-concierge", "Multilingual Concierge Service"},
	{"on-site-management", "On Site Management"},
	{"pool", "Pool"},
	{"postal-service", "Postal Service"},
	{"resident-services", "Resident Services"},
	{"restaurant", "Restaurant"},
	{"rock-climbing-area", "Rock Climbing Area"},
	{"secretarial-services", "Secretarial Services"},
	{"security-controlled-entrances", "Security Controlled Entrances"},
	{"security-system-video-monitor", "Security System with Video Monitor"},
	{"shared-office-space", "Shared Office Space"},
	{"shuttle-bus-service", "Shuttle Bus Service"},
	{"smoke-free-environment", "Smoke Free Environment"},
	{"smoke-heat-detectors", "Smoke and Heat Detectors"},
	{"squash-court", "Squash Court"},
	{"storage-lockers", "Storage Lockers"},
	{"table-tennis", "Table Tennis Room"},
	{"towel-and-linen-change", "Towel and Linen Change"},
	{"valet", "Valet"},
	{"vending-machine-foods-drinks", "Vending Machine with Foods & Drinks"},
	{"viewing-lounge", "Viewing Lounge"},
	{"wake-up-call-service", "Wake-up Call Service"},
}

// UnitAmenityTypes supported by the system
var UnitAmenityTypes = []*AmenityType{
	{"air-conditioning", "Air Conditioning"},
	{"air-purifier", "Air Purifier"},
	{"alarm-clock", "Alarm Clock"},
	{"apple-tv", "Apple TV"},
	{"baby-cribs", "Baby Cribs"},
	{"bathrobes", "Bathrobes"},
	{"blackout-blind", "Blackout Blind"},
	{"bluetooth-speaker-alarm", "Bluetooth Speaker/Alarm"},
	{"broadband-tv", "Broadband TV"},
	{"bvlgari-toiletries", "Bvlgari Toiletries"},
	{"cable-tv", "Cable TV"},
	{"chimney-exhaust-hood", "Chimney Exhaust Hood"},
	{"coffee-table", "Coffee Table"},
	{"complimentary-bottled-water", "Complimentary Bottled Water"},
	{"conventional-oven", "Conventional Oven"},
	{"daily-maid-service", "Daily Maid Service"},
	{"desk", "Desk"},
	{"dining-table", "Dining Table"},
	{"dishwasher", "Dishwasher"},
	{"dresser-table", "Built-in Dresser Table"},
	{"dvd-player", "DVD Player"},
	{"electric-hob", "Electric Hob"},
	{"electronic-keycard-access", "Electronic Keycard Access"},
	{"elevator-opens-into-home", "Elevator opens into Home"},
	{"exhaust-fan", "Exhaust Fan"},
	{"fully-equipped-kitchen", "Fully Equipped Kitchen"},
	{"hair-dryer", "Hair Dryer"},
	{"handy-smartphone", "Handy Smartphone"},
	{"heat-plate", "Heat Plate"},
	{"hi-fi-audio-system", "Hi-Fi Audio System"},
	{"housekeeping", "Daily Housekeeping"},
	{"individual-climate-control", "Individual Climate Control"},
	{"international-plug-system", "International Plug System"},
	{"ipod-dock", "iPod Dock"},
	{"iron-and-ironing-board", "Iron and Ironing Board"},
	{"lcd-tv", "LCD TV"},
	{"luggage-rack", "Luggage Rack"},
	{"microwave-with-grill", "Microwave with Grill"},
	{"minibar", "Minibar"},
	{"multimedia-connectivity-panels", "Multimedia Connectivity Panels"},
	{"nespresso-machine", "In-room Nespresso Machine"},
	{"phone", "Phone"},
	{"private-terrace", "Private Terrace"},
	{"rain-shower", "Rain Shower"},
	{"refrigerator", "Refrigerator"},
	{"rollaway-bed", "Rollaway Bed"},
	{"safe", "Safe"},
	{"shoe-cabinet", "Built-in Shoe Cabinet"},
	{"shoe-shine-bag", "Shoe Shine Bag"},
	{"stationery-kit", "Stationery Kit"},
	{"study-desk", "Study Desk"},
	{"toaster", "Toaster"},
	{"town-gas", "Town Gas"},
	{"tv-games-console", "Popular TV Games Console"},
	{"wall-to-wall-carpeting", "Wall-to-wall Carpeting"},
	{"washing-machine-with-drier", "Washing Machine with Drier function"},
	{"wifi", "Wifi"},
	{"wine-cellar", "Wine Cellar"},
	{"wine-cooler", "Wine Cooler"},
	{"wireless-phone", "Wireless Phone"},
}

// AmenityTypes are all amenity types supported
var AmenityTypes = append(PropertyAmenityTypes, UnitAmenityTypes...)
