package flentities

// AmenityType represents a recognized amenity type
type AmenityType struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// PropertyAmenityTypes supported by the system
var PropertyAmenityTypes = []*AmenityType{
	&AmenityType{"24-hour-concierge", "24-hour Concierge Service"},
	&AmenityType{"24-hour-maintenance", "24-hour Maintenance Services"},
	&AmenityType{"24-hour-security", "24-hour Security"},
	&AmenityType{"airport-pick-up", "Airport Pick Up"},
	&AmenityType{"art-gallery", "Art Gallery"},
	&AmenityType{"babysiting", "Babysiting Service"},
	&AmenityType{"business-centre", "Business Centre"},
	&AmenityType{"car-park", "Car Park"},
	&AmenityType{"childrens-party-room", "Children's Party Room"},
	&AmenityType{"complimentary-newspaper-magazine", "Complimentary Newspaper and Magazine"},
	&AmenityType{"computer-workstations", "Computer Workstations"},
	&AmenityType{"concierge", "Concierge"},
	&AmenityType{"daily-maid", "Daily Maid Service"},
	&AmenityType{"daycare", "Daycare"},
	&AmenityType{"dedicated-mobile-app", "Dedicated Mobile App"},
	&AmenityType{"disabled-room", "Disabled Room"},
	&AmenityType{"dry-cleaning", "Dry Cleaning"},
	&AmenityType{"dvd-library", "DVD Library"},
	&AmenityType{"e-centre", "E-Centre"},
	&AmenityType{"evening-turndown", "Evening Turndown Service"},
	&AmenityType{"fitness room", "Fitness Room"},
	&AmenityType{"flexible-terms", "Flexible Terms"},
	&AmenityType{"food-delivery-service", "Food Delivery Service"},
	&AmenityType{"foreign-exchange", "Foreign Exchange"},
	&AmenityType{"gift-shop", "Gift Shop"},
	&AmenityType{"gym", "Gym"},
	&AmenityType{"indoor-basketball-court", "Indoor Basketball Court"},
	&AmenityType{"indoor-childrens-playroom", "Indoor Children's Playroom"},
	&AmenityType{"it-engineering-support", "IT & Engineering Support"},
	&AmenityType{"karaoke-room", "Karaoke Room"},
	&AmenityType{"laundry", "Laundry"},
	&AmenityType{"library", "Library"},
	&AmenityType{"lifestyle-cafe", "Lifestyle Café"},
	&AmenityType{"limousine", "Limousine Service"},
	&AmenityType{"mail-message-delivery", "Mail and Message Delivery"},
	&AmenityType{"medical-assistance-referrals", "Medical Assistance Referrals"},
	&AmenityType{"meeting-rooms", "Meeting Rooms"},
	&AmenityType{"mini-mart", "Mini-Mart"},
	&AmenityType{"multilingual-concierge", "Multilingual Concierge Service"},
	&AmenityType{"on-site-management", "On Site Management"},
	&AmenityType{"pool", "Pool"},
	&AmenityType{"postal-service", "Postal Service"},
	&AmenityType{"resident-services", "Resident Services"},
	&AmenityType{"restaurant", "Restaurant"},
	&AmenityType{"rock-climbing-area", "Rock Climbing Area"},
	&AmenityType{"secretarial-services", "Secretarial Services"},
	&AmenityType{"security-controlled-entrances", "Security Controlled Entrances"},
	&AmenityType{"security-system-video-monitor", "Security System with Video Monitor"},
	&AmenityType{"shared-office-space", "Shared Office Space"},
	&AmenityType{"shuttle-bus-service", "Shuttle Bus Service"},
	&AmenityType{"smoke-free-environment", "Smoke Free Environment"},
	&AmenityType{"smoke-heat-detectors", "Smoke and Heat Detectors"},
	&AmenityType{"squash-court", "Squash Court"},
	&AmenityType{"storage-lockers", "Storage Lockers"},
	&AmenityType{"table-tennis", "Table Tennis Room"},
	&AmenityType{"towel-and-linen-change", "Towel and Linen Change"},
	&AmenityType{"valet", "Valet"},
	&AmenityType{"vending-machine-foods-drinks", "Vending Machine with Foods & Drinks"},
	&AmenityType{"viewing-lounge", "Viewing Lounge"},
	&AmenityType{"wake-up-call-service", "Wake-up Call Service"},
}

// UnitAmenityTypes supported by the system
var UnitAmenityTypes = []*AmenityType{
	&AmenityType{"air-conditioning", "Air Conditioning"},
	&AmenityType{"air-purifier", "Air Purifier"},
	&AmenityType{"alarm-clock", "Alarm Clock"},
	&AmenityType{"apple-tv", "Apple TV"},
	&AmenityType{"baby-cribs", "Baby Cribs"},
	&AmenityType{"bathrobes", "Bathrobes"},
	&AmenityType{"blackout-blind", "Blackout Blind"},
	&AmenityType{"bluetooth-speaker-alarm", "Bluetooth Speaker/Alarm"},
	&AmenityType{"broadband-tv", "Broadband TV"},
	&AmenityType{"bvlgari-toiletries", "Bvlgari Toiletries"},
	&AmenityType{"cable-tv", "Cable TV"},
	&AmenityType{"chimney-exhaust-hood", "Chimney Exhaust Hood"},
	&AmenityType{"coffee-table", "Coffee Table"},
	&AmenityType{"complimentary-bottled-water", "Complimentary Bottled Water"},
	&AmenityType{"conventional-oven", "Conventional Oven"},
	&AmenityType{"daily-maid-service", "Daily Maid Service"},
	&AmenityType{"desk", "Desk"},
	&AmenityType{"dining-table", "Dining Table"},
	&AmenityType{"dishwasher", "Dishwasher"},
	&AmenityType{"dresser-table", "Built-in Dresser Table"},
	&AmenityType{"dvd-player", "DVD Player"},
	&AmenityType{"electric-hob", "Electric Hob"},
	&AmenityType{"electronic-keycard-access", "Electronic Keycard Access"},
	&AmenityType{"elevator-opens-into-home", "Elevator opens into Home"},
	&AmenityType{"exhaust-fan", "Exhaust Fan"},
	&AmenityType{"fully-equipped-kitchen", "Fully Equipped Kitchen"},
	&AmenityType{"hair-dryer", "Hair Dryer"},
	&AmenityType{"handy-smartphone", "Handy Smartphone"},
	&AmenityType{"heat-plate", "Heat Plate"},
	&AmenityType{"hi-fi-audio-system", "Hi-Fi Audio System"},
	&AmenityType{"housekeeping", "Daily Housekeeping"},
	&AmenityType{"individual-climate-control", "Individual Climate Control"},
	&AmenityType{"international-plug-system", "International Plug System"},
	&AmenityType{"ipod-dock", "iPod Dock"},
	&AmenityType{"iron-and-ironing-board", "Iron and Ironing Board"},
	&AmenityType{"lcd-tv", "LCD TV"},
	&AmenityType{"luggage-rack", "Luggage Rack"},
	&AmenityType{"microwave-with-grill", "Microwave with Grill"},
	&AmenityType{"minibar", "Minibar"},
	&AmenityType{"multimedia-connectivity-panels", "Multimedia Connectivity Panels"},
	&AmenityType{"nespresso-machine", "In-room Nespresso Machine"},
	&AmenityType{"phone", "Phone"},
	&AmenityType{"private-terrace", "Private Terrace"},
	&AmenityType{"rain-shower", "Rain Shower"},
	&AmenityType{"refrigerator", "Refrigerator"},
	&AmenityType{"rollaway-bed", "Rollaway Bed"},
	&AmenityType{"safe", "Safe"},
	&AmenityType{"shoe-cabinet", "Built-in Shoe Cabinet"},
	&AmenityType{"shoe-shine-bag", "Shoe Shine Bag"},
	&AmenityType{"stationery-kit", "Stationery Kit"},
	&AmenityType{"study-desk", "Study Desk"},
	&AmenityType{"toaster", "Toaster"},
	&AmenityType{"town-gas", "Town Gas"},
	&AmenityType{"tv-games-console", "Popular TV Games Console"},
	&AmenityType{"wall-to-wall-carpeting", "Wall-to-wall Carpeting"},
	&AmenityType{"washing-machine-with-drier", "Washing Machine with Drier function"},
	&AmenityType{"wifi", "Wifi"},
	&AmenityType{"wine-cellar", "Wine Cellar"},
	&AmenityType{"wine-cooler", "Wine Cooler"},
	&AmenityType{"wireless-phone", "Wireless Phone"},
}

// AmenityTypes are all amenity types supported
var AmenityTypes = append(PropertyAmenityTypes, UnitAmenityTypes...)
