[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.6"

[[constraint]]
  branch = "master"
  name = "github.com/rdumont/assistdog"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[override]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.4.0"
