[metadata.heroku]
  root-package = "github.com/nerde/fuji-lane-back"
  install = ["./cmd/..."]
  go-version = "go1.11"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/DATA-DOG/godog"
  version = "0.7.6"

[[constraint]]
  branch = "master"
  name = "github.com/rdumont/assistdog"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[override]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.4.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.45"

[[constraint]]
  name = "github.com/go-test/deep"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/icrowley/fake"

[[constraint]]
  name = "github.com/jordan-wright/email"
  version = "3.0.0"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sendgrid/sendgrid-go"
  version = "3.4.1"
